config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  resources :squares
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/square.rb
class Square < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController
  before_action :set_square, only: [:show, :edit, :update, :destroy]

  # GET /squares
  # GET /squares.json
  def index
    squares = Square.all
    render json: squares
  end

  # GET /squares/1
  # GET /squares/1.json
  def show
    if set_square
      render json: set_square
    else
      render json: set_square.errors
    end
  end

  # GET /squares/new
  def new
    @square = Square.new
  end

  # GET /squares/1/edit
  def edit
  end

  # POST /squares
  # POST /squares.json
  def create
    @square = Square.new(square_params)

      if @square.save
        render json: @square, status: :created
      else
        render json: @square.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /squares/1
  # PATCH/PUT /squares/1.json
  def update
    respond_to do |format|
      if @square.update(square_params)
        format.html { redirect_to @square, notice: 'Square was successfully updated.' }
        format.json { render json: @square, status: :created }
      else
        format.html { render :edit }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squares/1
  # DELETE /squares/1.json
  def destroy
    @square.destroy
    respond_to do |format|
      format.html { redirect_to squares_url, notice: 'Square was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_square
      @square = Square.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def square_params
      params.require(:square).permit(:matrix)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerfectSquare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'Index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/squares/_form.html.erb
<%= form_with(model: square, local: true) do |form| %>
  <% if square.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(square.errors.count, "error") %> prohibited this square from being saved:</h2>

      <ul>
        <% square.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matrix %>
    <%= form.text_field :matrix %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/squares/edit.html.erb
<h1>Editing Square</h1>

<%= render 'form', square: @square %>

<%= link_to 'Show', @square %> |
<%= link_to 'Back', squares_path %>

app/views/squares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Squares</h1>

<table>
  <thead>
    <tr>
      <th>Matrix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @squares.each do |square| %>
      <tr>
        <td><%= square.matrix %></td>
        <td><%= link_to 'Show', square %></td>
        <td><%= link_to 'Edit', edit_square_path(square) %></td>
        <td><%= link_to 'Destroy', square, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Square', new_square_path %>

app/views/squares/new.html.erb
<h1>New Square</h1>

<%= render 'form', square: @square %>

<%= link_to 'Back', squares_path %>

app/views/squares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matrix:</strong>
  <%= @square.matrix %>
</p>

<%= link_to 'Edit', edit_square_path(@square) %> |
<%= link_to 'Back', squares_path %>